### PR TITLE
Stop pestering users for agreement every time the device is connected

### PR DESCRIPTION
**Pull request by rmaruszewski**

### CODE REVIEW

**Comment by sanchin** [comment]
Hm, I thought I already tried that when creating the original implementation and it didn't work for some reason. 

I'm slightly concerned that this will make the application react to ANY usb device connected. So if you have a USB keyboard or whatever (does anyone still use them?), I think it'll trigger the app.

**Comment by pskowronek** [comment]
@sanchin point is sound, however let's try to figure out the way to solve the problem this way or another.

Let's take Torque app as an example. Now, when I connect the PM device while no apps are opened I get a question as to whether to open Torque for it (probably they have similar setting as proposed by @rmaruszewski ). This is of course not very nice. If I have PM station app already opened and I attach the device then I'm asked twice as to whether open Torque or PM station. Very annoying I must admit.

IMHO the main thing is why when asked what app to open and having an option to select a default app for that particular device the setting is somehow lost and not obeyed the second time the device is connected. Maybe this is the real cause, i.e. to let the system remember what app should be opened for that particular device?

**Comment by sanchin** [comment]
I remember reading that the "remember device" settings are lost after disconnecting the device. It's either being connected under different handle or Android's plain dumb. The setting was supposed to work with apps that you turn on and off while the device (or a couple of them) is connected, so that it does not ask for permission each time. After disconnecting - its entire record is being removed.

**Comment by pskowronek** [comment]
@sanchin can you take a look here: https://stackoverflow.com/a/15151075 - I know it is relatively old answer and you already probably saw it. Maybe we should add a couple of usb serial vendor ids there so 'remember' function could work?

**Comment by sanchin** [comment]
Yep, I saw that answer. It should be good for users with the same devices we have or the ones we helped them get. That's something at least.

EDIT to clarify - those ID's go with the solution @rmaruszewski implemented, so the application won't ask for permission at all for these. It will probably just prompt you to choose an application if you have more than 1 that can use USB

**Comment by rmaruszewski** [comment]
This solution does work fine after setting the right vendor-id and product-id (you have to set both). If you set wrong values you'll get prompted for agreement every single time. For me the proper values are vendor-id="1027" product-id="24577", you can check if they work for you too.

**Comment by pskowronek** [comment]
@rmaruszewski the vendor id & product id you have just pushed, what serial device they belong to? FT232 or PL2303?

**Comment by rmaruszewski** [comment]
FT232

**Comment by pskowronek** [comment]
@rmaruszewski , cool.
@rjaros87 , can you provide PL2303 vendor id and product id to add to this commit?

**Comment by rjaros87** [comment]
- For PL2303 
  Product ID: 0x2303
  Vendor ID: 0x067b (Prolific Technology, Inc.)
  To Decimal: productId: 8963, vendorId: 1659

- For CP210X 
  Product ID: 0x7523
  Vendor ID: 0x1a86
  To Decimal: productId: 29987, vendorId: 6790

**Comment by pskowronek** [comment]
@rmaruszewski are you able to add these 2 devices stated by Radek to your PR?

**Comment by rjaros87** [comment]
So I think we could merge it. It's good enough for me.

**Pull request merged**
